# SwiftLint Configuration
# https://github.com/realm/SwiftLint

# Paths to include
included:
  - Application
  - App
  - Coordinator
  - Model
  - Services
  - Toolbox
  - UI
  - ViewModel

# Paths to exclude
excluded:
  - "*/Generated/*"
  - "*/Tests/*"
  - "*/.build/*"
  - "*/DerivedData/*"

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
  - opening_brace
  - statement_position

# Opt-in rules
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ok
    - to
    - x
    - y
    - i
    - j
    - p1

nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 3
    error: 5

cyclomatic_complexity:
  warning: 15
  error: 25

type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 50
    error: 60

# Custom rules
custom_rules:
  no_print:
    name: "No print statements"
    regex: "\\bprint\\s*\\("
    message: "Use Logger instead of print()"
    severity: warning
    match_kinds:
      - identifier
